name: DanFelytraFly
version: '${project.version}'
main: com.janjidan.danfelytrafly.DanFelytraFly
api-version: '1.20'
depend: [ ProtocolLib ]
commands:
  danfelytrafly:
    permission: op
    aliases:
      - def